name: fridge_yellow_team_bloc
description: A new Flutter project.

version: 0.5.4+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  http: ^0.13.3
  dio: ^4.0.1
  logger: ^1.1.0
  google_fonts: ^2.1.0
  carousel_slider: ^4.0.0

  flutter_secure_storage: ^4.2.1
  firebase_messaging: ^10.0.9
  firebase_core: ^1.8.0
  firebase_database: ^8.0.1
  flutter_local_notifications: ^9.0.1
  overlay_support: ^1.2.1

  cached_network_image: ^3.1.0
  url_launcher: ^6.0.10
  photo_view: 0.13.0
  share: ^2.0.4
  device_info: ^2.0.3

  cupertino_icons: ^1.0.3
  flutter_screenutil: ^5.0.0+2

  confetti: ^0.6.0
  visibility_detector: ^0.2.2
  hive: ^2.0.4
  path_provider: ^2.0.4
  google_sign_in: ^5.1.0
  stream_transform: ^2.0.0
  flutter_notification_channel: ^2.0.0
  freezed_annotation: ^0.14.2
  json_annotation: ^4.0.0
  flutter_bloc: ^7.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  analyzer: ^1.7.1
  build_resolvers: ^2.0.4
  json_serializable: ^4.1.0
  build_runner: ^2.1.2
  flutter_launcher_icons: ^0.9.2
  freezed: ^0.14.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/png/mc_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/gif/